# https://github.com/espressif/esp-idf-ci-action
name: Compile ESP-IDF

on:
  push:
    tags:
        - "v*.*.*"
#    branches:
#      - master

env:
    APP_NAME: hello

permissions:
    contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    name: Build and deploy

    steps:
        - name: Checkout
          uses: actions/checkout@v2
#          with:
#            submodules: 'recursive'
        - name: ESP-IDF Build
          uses: espressif/esp-idf-ci-action@v1
          with:
            esp_idf_version: v4.4
            target: esp32

        - name: Put variable into the ENV
          run: echo "app_name=$APP_NAME" >> $GITHUB_ENV

        - name: Copy firmware
          run: cp build/hello_world.bin ./${APP_NAME}.bin

        - name: Push to release
          uses: softprops/action-gh-release@v1
          if: startsWith(github.ref, 'refs/tags/')
          with:
              files: ${{ env.app_name }}.bin
              body_path: CHANGELOG.md

