name: Compile ESP-IDF

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up ESP-IDF
        uses: espressif/setup-esp-idf@v2
        with:
          esp-idf-version: latest
          esp-idf-target: esp32
      - name: Compile
        run: idf.py build
